### ISSUE TITLE
Fix Netlify Deploy

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/website#118]
Currently the deploy of our master branch fails with the following message. Most likely this is related to some changes in the most recent merge or the netlify config itself. 

Check out the following logs: 
https://app.netlify.com/sites/centrifuge-website/deploys/5cc15849d69c3395af54be98

**Comment by mayalouise** [comment]
Feature Req

**Comment by Aronods** [comment]
PR: #120

**Comment by pstehlik** [comment]
Hey @Aronods can you re-open the PR to merge into develop instead of merging into master?

**Comment by Aronods** [comment]
@pstehlik sure here it's the new PR: #123 .

Because of the `Currently the deploy of our master branch fails` in the description, I assumed this issue refers directly to master

**Comment by lucasvo** [comment]
@Aronods we always merge into develop first and test on the staging site before doing a release by merging develop into master.
