### ISSUE TITLE
Tweak Footer

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/website#155]
We have to make a few small tweaks in the footer:
1) The EU Logo needs to be slightly larger
2) Remove the physical addresses
3) Change the "(c) Centrifuge Inc."  sentence to: Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/) license.

**Comment by stascentrifuge** [comment]
[Footer and Flag.zip](https://github.com/centrifuge/website/files/3869339/Footer.and.Flag.zip)

**Comment by stascentrifuge** [comment]
![Footer](https://user-images.githubusercontent.com/47028394/69241683-4c459680-0bb0-11ea-933e-e659ebc1e68f.png)

**Comment by lucasvo** [comment]
@eswarasai would you like to work on this?

**Comment by eswarasai** [comment]
@lucasvo - Thanks for the heads up. Yeah, sure. I think the issue has all the needed assets. Let me quickly dive into it and update you in the next couple of hours :)

**Comment by mayalouise** [comment]
Any updates @eswarasai? Let us know if you have any questions

**Comment by eswarasai** [comment]
@mayalouise - Just pushed the code and created a PR #157 with attached screenshots. Thanks!
