### ISSUE TITLE
Change Navigation Bar: Add "Products" menu item with 2 dropdown subpages: add new subpage DTFin and migrate Tinlake 

### ISSUE THREAD

**Issue by mayalouise** [centrifuge/website#156]
**Change Navigation bar:**
- Add "Products" to Navigation bar. 
- Enable dropdown with 2 sub-categories (Tinlake, Deep Tier Financing), linking to two pages:
1) Tinlake (Current Tinlake page content needs to be migrated from its current location under "Technology" https://centrifuge.io/technology/tinlake). Note that the Tinlake subpage will be updated as well (https://github.com/centrifuge/website/issues/159)
2) Deep Tier Financing (New subpage to be added)
Wireframe for desk and mobile are attached as jpgs, with one, or two remarks in red to explain required functionality. Sketch file also attached.

Copy here: https://docs.google.com/document/d/1Df26raIZQwG7PE6ID5m_F_2pFYkD3TQtUVbHtC3g5-c

Desktop Wireframe below:
![image](https://user-images.githubusercontent.com/48755923/74137469-28fb1800-4bf0-11ea-86b2-fa0125223912.png)

**Comment by mayalouise** [comment]
[Assets.zip](https://github.com/centrifuge/website/files/3898099/Assets.zip)

**Comment by mayalouise** [comment]
Hi @eswarasai would you like to work on this?

**Comment by eswarasai** [comment]
@mayalouise - Sure. I'll get started on it over the weekend. Thanks 🙂

**Comment by denniswell** [comment]
Sketch and JPGS for desktop and mobile wireframes here:
[DTFin_subpage_wireframe_SketchandJPGs.zip](https://github.com/centrifuge/website/files/4179956/DTFin_subpage_wireframe_SketchandJPGs.zip)

**Comment by denniswell** [comment]
[DTFin_Assets.zip](https://github.com/centrifuge/website/files/4180057/DTFin_Assets.zip)
