### ISSUE TITLE
Update News subpage on centrifuge.io

### ISSUE THREAD

**Issue by denniswell** [centrifuge/website#160]
(i) Delete the `Press about Centrifuge` section

![image](https://user-images.githubusercontent.com/48755923/74075602-8b4af180-4a13-11ea-8b8c-76505de6510f.png)

(ii)In the You tube section, replace `More videos` with `Please find more videos in our YouTube channel`

![image](https://user-images.githubusercontent.com/48755923/74075689-057b7600-4a14-11ea-8e6e-9cd8a5ea68e3.png)

**Comment by lucasvo** [comment]
@denniswell why do you want to replace the label for "More videos"?

**Comment by denniswell** [comment]
Because I feel it gets lost. I actually didn't notice the link, so thought longer text will make it more visible... Bot not a strong opinion on that. If you feel status quo is better/enough, all good

**Comment by lucasvo** [comment]
@denniswell let's add a button here instead.
