### ISSUE TITLE
Title underline is too short?

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/website#3]
<img width="1074" alt="screen shot 2019-01-24 at 10 26 23" src="https://user-images.githubusercontent.com/31727/51668512-45fb8380-1fba-11e9-899b-b954ff8656b4.png">

**Comment by mirshko** [comment]
is that sarcastic? liek its too long or it should be full width?

**Comment by lucasvo** [comment]
It probably should be full width, right? I would refer to Stas.

**Comment by mirshko** [comment]
made it full width of the container.
