### ISSUE TITLE
About — 6 people instead of 4. And no scrolling...

### ISSUE THREAD

**Issue by stascentrifuge** [centrifuge/website#30]
About — 6 people here instead of 4. And no scrolling...
<img width="1111" alt="2019-01-31 13 00 21" src="https://user-images.githubusercontent.com/47028394/52048509-9e9fc300-255c-11e9-8dc0-f21241d7da06.png">

**Comment by mirshko** [comment]
@stascentrifuge for now we will just have a list of them all. we need to find a slider component for later.
