### ISSUE TITLE
News Logos

### ISSUE THREAD

**Issue by stascentrifuge** [centrifuge/website#31]
News — Can you please align logo right. So the gap between logo and text became 32 px.
<img width="851" alt="2019-01-31 12 59 59" src="https://user-images.githubusercontent.com/47028394/52048549-b8410a80-255c-11e9-8983-078e218b24f8.png">

**Comment by mirshko** [comment]
@stascentrifuge grommet doesn't support 32px sizing in its spacing options. i think 48 looks clean. is that okay?
