### ISSUE TITLE
https://centrifuge.io/issuers/ "Join the Community" CTA not working

### ISSUE THREAD

**Issue by devinblack1337** [centrifuge/website#324]
This CTA on https://centrifuge.io/issuers/ does not work for me on Chrome, Mac OS. When I click on it, nothing happens. I'm not getting any error messages in console on click.

![image](https://user-images.githubusercontent.com/82221522/132905792-0fcc36f6-0b0b-4c6e-b7ab-5f800dc147ec.png)

**Comment by denniswell** [comment]
Please link to: gov.centrifuge.io
