### ISSUE TITLE
Correct alignment and add contacts

### ISSUE THREAD

**Issue by ImdioR** [centrifuge/website#330]
Correct alignment and add contacts to official channels: discord, TG, Github and ecc.

![contacts](https://user-images.githubusercontent.com/90972248/133921909-25a039a6-678b-491d-be41-ea7427007d20.jpg)
![allign](https://user-images.githubusercontent.com/90972248/133921911-930a8186-86bc-419c-8043-c39c1dba155f.jpg)

**Comment by lucasvo** [comment]
@ImdioR can you move this to github.com/centrifuge/documentation ? Thanks!
