### ISSUE TITLE
Wrong Altair reward https://centrifuge.io/altair/

### ISSUE THREAD

**Issue by ImdioR** [centrifuge/website#367]
Source: https://centrifuge.io/altair/

Wrong info: 
KSM Reward:  400 AIR : 1 KSM
![wrongasd](https://user-images.githubusercontent.com/90972248/140652665-16fb7e8c-7430-4f75-a054-b2d354df60d7.png)

Correct info:  
![wrongcorr](https://user-images.githubusercontent.com/90972248/140652670-cc1ad6fa-8fd5-4158-bd77-e0bc3f9acc13.png)

KSM Reward:  430 AIR : 1 KSM

**Comment by denniswell** [comment]
Thanks, we need to update the page with the result anyways
