### ISSUE TITLE
altair claim page - does not show all acounts

### ISSUE THREAD

**Issue by SvenMeyer** [centrifuge/website#371]
I am trying to claim AIR on [https://centrifuge.io/altair/crowdloan/](https://centrifuge.io/altair/crowdloan/)

I see 6 of my accouns in the list. However, although the visibilty is set to "Allow use on any chain", (just) the account I used to contribute does not show up.

What's the problem ?

**Comment by SvenMeyer** [comment]
I changed the visibility for the account I used for the crowdload to "Kusama", reloaded the page, and then it was visible.

Would be great to mention that at least somewhere, better fix the code.

**Comment by SvenMeyer** [comment]
That did not work (for me).

![image](https://user-images.githubusercontent.com/25609/141963662-0983d772-452d-42d9-94fa-8a7576a0c47f.png)

**Comment by denniswell** [comment]
Sven, just double checking here, `Use allowed on any chain` did not work for you, only `Kusama` did?

Did you try `Use allowed on any chain` and reload the page
