### ISSUE TITLE
Improve structure of Documentation page

### ISSUE THREAD

**Issue by denniswell** [centrifuge/website#373]
Background/Issue:
How it currently works:
We basically have 3 Layers at the moment
Parts - Getting started, learn, Use Make… (L1)
Sections - First level of the parts (L2), this is also where already the page/content is
Subsections - These are already the subsections of each content/document which are a also displayed in the navigation panel (L3)
Only having 3 Layers and being forced to having all content already on L2 really narrows how we structure and grow the documentation. We can mainly grow horizontally  (splitting into more parts) and not vertically (going deeper into the Layers)

ACs
May ideal approach would be to have a infrastructure of 4 Layers (e.g. Parts, Segments, Sections, Subsections) where all 4 Layers are still displayed and navigated in the navigation bar, but where it is also possible to have content/the docs on L3 or L4. E.g. some parts perhaps don’t require 4 Layers others do. Then the Navigation pane most be smart enough to display this correctly.
Hope this was relatively clear, happy to also discuss on Monday and go through the docs to better explain the issue.

**Comment by lucasvo** [comment]
This should be moved to github.com/centrifuge/documentation

**Comment by denniswell** [comment]
See also current discussion here: https://gov.centrifuge.io/t/proposal-to-re-structure-update-the-official-centrifuge-documentation/3327

**Comment by denniswell** [comment]
Issue moved to [centrifuge/documentation #325](https://github.com/centrifuge/documentation/issues/325) via [**ZenHub**](https://www.zenhub.com/)
