### ISSUE TITLE
Website navigation: Add link to Governance Forum

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/website#398]
## Background
The Centrifuge website currently has 7 top level items:
1. Tinlake
2. Parachain
3. Issuers
4. CFG Token
5. About
6. Careers
7. Doc

Neither the main navigation nor the footer contains a link to the Governance forum on https://gov.centrifuge.io/.

## Approach
Each page on the Centrifuge website should offer a link to the Forum, as it's important for a protocol/marketplace to give proof of decentralization.

## Access criteria
(Decide on just one solution)
A) Add item "Governance" to main navigation at position 5 (after CFG Token)
B) Add item "Governance forum" to footer links at position 1 (on top of Data Privacy Policy)

**Comment by Shermanoide** [comment]
Hello, I did formulate the same idea on the discord group.
In my opinion this would be a great addition. The governance forum will gain in attractivity and visibility if this is implemented. 
Ps: Almost every other defi protocol are doing it this way ;)
