### ISSUE TITLE
DNS Entries

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/website#43]
prepare the following DNS records in netlify

Type | Host | Value | TTL |  
-- | -- | -- | -- | --
A Record | metadata | 35.239.99.220 | Automatic | Remove
A Record | www | 68.65.123.243 | 5 min | Remove
CNAME Record | developer | centrifuge.github.io. | Automatic | Remove
URL Redirect Record | @ | http://www.centrifuge.io  |   | Remove
TXT Record | @ | google-site-verification=n1rGr5jsEm-J0sL3uq_Yg3Vd7Fz3N4TOYchLG0232Mw | Automatic | Remove
ADD NEW RECORDSHOW MORE

Type | Host | Value | TTL |  
-- | -- | -- | -- | --
MX Record | @ | ASPMX.L.GOOGLE.COM.1 | 5 min | Remove
MX Record | @ | ALT1.ASPMX.L.GOOGLE.COM.5 | 1 min | Remove
MX Record | @ | ALT2.ASPMX.L.GOOGLE.COM.5 | 1 min | Remove
MX Record | @ | ASPMX2.GOOGLEMAIL.COM.10 | 1 min | Remove
MX Record | @ | ASPMX3.GOOGLEMAIL.COM.10 | 1 min | Remove
ADD NEW RECORD

**Comment by mirshko** [comment]
@lucasvo dns entries added to Netlify.
```
dns1.p01.nsone.net
dns2.p01.nsone.net
dns3.p01.nsone.net
dns4.p01.nsone.net
```

these are the nameservers to switch to when ready.
