### ISSUE TITLE
Altair Page still asks to "Join Crowdloan"

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/website#443]
This page currently asks users to join the crowdloan instead of linking to app.altair.network 

https://centrifuge.io/altair

**Comment by EstherCentrifuge** [comment]
1. Remove newsletter
2. CTA on top "Enter Altair Application"
3. CTA on bottom -> join the community Link: https://gov.centrifuge.io/c/altair/40

**Comment by EstherCentrifuge** [comment]
The new menu should get a black BG on this page, and the "Centrifuge App" Button should state "Altair App" and link the the altair application on this page only! 

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/407fa637-484d-4332-8e54-b0ec5c37d10c)

**Comment by annamehr** [comment]
Not part of new altair page anymore https://centrifuge.io/altair/crowdloan
