### ISSUE TITLE
/brand/ "Storybook" link broken

### ISSUE THREAD

**Issue by devinblack1337** [centrifuge/website#451]
The link at the bottom of [https://centrifuge.io/brand/](https://centrifuge.io/brand/), "Visit the Storybook", is broken. It leads to https://axis.centrifuge.io/ which seems to no longer exist.

**Comment by denniswell** [comment]
Closing here with work on new website starting soon

**Comment by EstherCentrifuge** [comment]
My appologies for the very late reply, this will be solved in the next update of the website where there will no longer be a "visit the storybook" action. I'll close this ticket now thanks
