### ISSUE TITLE
Altair Claiming - Failed to Construct URL, Crowdloanclaim.outofleaseperiod.

### ISSUE THREAD

**Issue by ImdioR** [centrifuge/website#633]
**Describe the bug**

**To Reproduce**
1. Go to https://centrifuge.io/altair/crowdloan
![image](https://user-images.githubusercontent.com/90972248/209453774-e4a2ba25-8da0-4fd7-b56e-15ebd2e219a9.png)
2. Click on claim
![image](https://user-images.githubusercontent.com/90972248/209453780-be8c7b12-3a8a-4a9a-9d36-a7d63a249d39.png)
![image](https://user-images.githubusercontent.com/90972248/209453791-6f4f0c07-ff04-4b13-9535-acb2ef6ad60f.png)

3. After claiming the user is redirected to the white page. 
![image](https://user-images.githubusercontent.com/90972248/209453785-2dd5379d-6496-4725-8c36-6f9d15711d58.png)
4. Result: Claiming unsuccessful:
![image](https://user-images.githubusercontent.com/90972248/209453770-23984552-229f-44c5-b4e5-db95807a0585.png)

Console Description:
![image](https://user-images.githubusercontent.com/90972248/209453841-53d2ad81-3ddc-4c3b-bc67-0db7f609b7ce.png)

![image](https://user-images.githubusercontent.com/90972248/209453797-08269114-d859-457d-b015-39c520c53e42.png)

**Expected behavior**

**Desktop 
User tried different browsers but the result is always the same. White page.

**Additional context**
If you need the wallet address please contact me in Discord.

**Comment by ImdioR** [comment]
Another user reported the same issue 
https://altair.subscan.io/extrinsic/0x5f11c3d5757b287a8f527243069029b2432a87ca3bb14c54abaa69a60b03cf44

![image](https://user-images.githubusercontent.com/90972248/210623084-49edc7c2-c71f-4d1c-8920-20d0101e4857.png)

**Comment by iamexe** [comment]
Hi, can I have an update on this issue please? 

It's been open for over a month now and I don't see any progress / interaction / comment.

I'm also not sure this is a website related issue.

Seems like an admin could extend the lease period within polkadot.js.org extrinsics but I'm not entirely sure.

Thanks for a quick feedback on the mather.

**Comment by ImdioR** [comment]
Should be solved now with Council Motion 88
https://gov.centrifuge.io/t/council-motion-88-set-lease-period-of-altair-parachain/5399/3

@iamexe can you try to claim your rewards now?

**Comment by iamexe** [comment]
I can confirm that it worked. Thanks.

**Comment by ImdioR** [comment]
Awesome! Happy to hear this and sorry for the delay!
I will close this ticket in 24h.
