### ISSUE TITLE
Homepage feedback

### ISSUE THREAD

**Issue by Hornebom** [centrifuge/website#639]
- fix Moire effect hero cyclone graphic
- restructure Working With list --> Have first five partners be BlockTower, Maker, Aave, Polkadot, Ethereum
- change “Assets Financed” -> “Total Assets Financed” 
- change “Total Assets Tokenized” -> “Assets Tokenized”
- link audit logos to audit reports
- remove acala logo

**Comment by ImdioR** [comment]
Hi
After migration, i think, that we lost the page with information about Altair:
https://centrifuge.io/altair/
![image](https://user-images.githubusercontent.com/90972248/211604270-2247b023-b663-4c77-8589-59d8163d35e6.png)

This one doesn`t work anymore.

**Comment by annamehr** [comment]
@ImdioR I'll remove your comment as we discussed to move Altair to the documentation
