### ISSUE TITLE
Need to have a GDPR consent/popup for cookies etc

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/website#64]
The site needs to have GDPR-compliant cookie popup for users to give consent. 
Not sure exactly what we need to comply, but we had that on the old site already as well.

Example: https://www.wpromote.com/blog/gdpr-cookie-consent-examples-user-consent

**Comment by mirshko** [comment]
@pstehlik hey there!

so I actually have experience with this topic from my last company. 

there is no **direct** clause saying you need a consent popup, this is direct information from a data privacy lawyer whose information I could get and link you two should you have additional questions!

**Comment by pstehlik** [comment]
Interesting. I'll leave @mayalouise the lead here. I had different info in the summer of last year but if that's changed and we don't have to have popups etc then that's great.

**Comment by mayalouise** [comment]
After researching, let's include a simple pop-up communicating our use of google analytics, linking to the updated privacy policy 
Stas is designing as I write this, will be sent to you @mirshko within the next hour

**Comment by mirshko** [comment]
@mayalouise i dont think we even need the popup. we just need to make sure the privacy policy is good.

**Comment by lucasvo** [comment]
How about a compromise of showing a notification bar at the bottom of the page that can be dismissed or ignored?

**Comment by mirshko** [comment]
@lucasvo that was the idea. gdpr popups should never interfere with viewing the page. Pretty sure google even marks pages lower SEO wise if you use popups.

@stascentrifuge something like this
<img width="1679" alt="screenshot 2019-02-08 15 40 17" src="https://user-images.githubusercontent.com/8116716/52484961-db506780-2bb7-11e9-8cdb-d73f6b6aa4be.png">

**Comment by mayalouise** [comment]
The above message is too vague. As a company that prides itself with protecting peoples data and privacy, we owe our visitors to notify them in a transparent way of what we information we retain. 

My suggestion is the following: 
"By continuing your visit on this site, you accept the use of cookies from Google Analytics so we can improve the site for you. Read more (link to privacy policy). (Accept) (Reject)" 

SEO on google, while not irrelevant, should not be a deciding factor imo

**Comment by mirshko** [comment]
I meant for SEO if you use full page popups. bottom banners should be fine @mayalouise.

Btw. if we want to let the user actually reject this and respect their right to not be tracked we need to use something like this. https://consently.co/ this doesn't load the trackers until they actually accept them.

**Comment by mirshko** [comment]
or this https://www.cookiehub.com/

**Comment by mayalouise** [comment]
Hi Jeff. Please remove the reject option and push the banner

**Comment by mirshko** [comment]
Awesome :)

Will work on this tomorrow! :3
