### ISSUE TITLE
Can’t claim a reward. Got an error message 

### ISSUE THREAD

**Issue by MaxDatii** [centrifuge/website#661]
**Describe the bug**
I tried to claim a reward from parachain auction. (I had some AIR available 0.007 AIR.) 

**To Reproduce**
1.Asked a friend to send me some AiR
2. He send me 0.007 AIR.
3. I went to https://centrifuge.io/altair/crowdloan
4. Saw my locked AIR
5. Pushed “Claim rewards” button. 
6. saw the error message:
7. “Claiming rewards” “transaction failed”
9. Pushed the button again. 
10. Saw the error message again (different):
11. Claiming rewards” “Air balance to low”

**Expected behavior**
Want to claim my locked rewards. I see 90.3 Locked AIR in “Total Rewards”

**Screenshots**
Added two screenshots 

**Desktop (please complete the following information):**
 - MacOS 13.2.1
 - Browser Chrome
 - Version 103.0.5060.134
![Uploading F2A19841-9688-4C84-8317-970AD216FBC2.jpeg…]()

**Comment by ImdioR** [comment]
Should be solved now with Council Motion 88
https://gov.centrifuge.io/t/council-motion-88-set-lease-period-of-altair-parachain/5399/3

@MaxDatii  can you try to claim your rewards now?
